### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Njc4NDExMDB9.OHNp_d2LjKTiAIYZbOTy0zUgVt9Q2xn1964reBaZna4