### Ingredients index
GET http://localhost:3000/ingredients.json

### Ingredients create
POST http://localhost:3000/ingredients.json
Content-Type: application/json

{
  "name": "potatoes",
  "image_url": "potatoes.jpg"
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
# POST http://localhost:3000/photos.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Njc4NDExMDB9.OHNp_d2LjKTiAIYZbOTy0zUgVt9Q2xn1964reBaZna4
# Content-Type: application/json

# {
#   "name": "Test name",
#   "width": 640,
#   "height": 480
# }

